openapi: 3.0.0
info:
  title: Ticket Booking API
  version: 1.0.0
tags:
  - name: user
  - name: event
  - name: ticket
paths:
  /user:
    post:
      tags:
        - user
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
    get:
      tags:
        - user
      summary: Read all users
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Internal server error
  /user/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    get:
      tags:
        - user
      summary: Read the user by id
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'      
        '400':
          description: Invalid input
        '404':
          description: Entity not found
        '500':
          description: Internal server error
    put:
      tags:
        - user
      summary: Update the user by id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User' 
        '400':
          description: Invalid input
        '500':
          description: Internal server error
    patch:
      tags:
        - user
      summary: Updates the user with partial form data
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: first_name
          in: query
          schema:
            type: string
        - name: last_name
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'      
        '400':
          description: Invalid input
        '404':
          description: Entity not found
        '500':
          description: Internal server error
    delete:
      tags:
        - user
      summary: Delete the user by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '404':
          description: Entity not found
        '500':
          description: Internal server error
  /event:
    post:
      tags:
        - event
      summary: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
    get:
      tags:
        - event
      summary: Read all events
      responses:
        '200':
          description: List of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '500':
          description: Internal server error
  /event/{id}:
    get:
      tags:
        - event
      summary: Read the event by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'      
        '400':
          description: Invalid input
        '404':
          description: Entity not found
        '500':
          description: Internal server error
    put:
      tags:
        - event
      summary: Update the event by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Event updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
    patch:
      tags:
        - event
      summary: Updates the event with partial form data
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: name
          in: query
          schema:
            type: string
        - name: date
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Invalid input
        '404':
          description: Entity not found
        '500':
          description: Internal server error
    delete:
      tags:
        - event
      summary: Delete the event by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '404':
          description: Entity not found
        '500':
          description: Internal server error
  /ticket:
    post:
      tags:
        - ticket
      summary: Create a new ticket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ticket'
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
    get:
      tags:
        - ticket
      summary: Read all tickets
      responses:
        '200':
          description: List of tickets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ticket'
        '500':
          description: Internal server error
  /ticket/{id}:
    get:
      tags:
        - ticket
      summary: Read the ticket by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'      
        '400':
          description: Invalid input
        '404':
          description: Entity not found
        '500':
          description: Internal server error
    put:
      tags:
        - ticket
      summary: Update the ticket by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ticket'
      responses:
        '200':
          description: Ticket updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
    patch:
      tags:
        - ticket
      summary: Updates the ticket with partial form data
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: status
          in: query
          schema:
            type: string
            enum: ['booked', 'sold', 'canceled']
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        '400':
          description: Invalid input
        '404':
          description: Entity not found
        '500':
          description: Internal server error
    delete:
      tags:
        - ticket
      summary: Delete the ticket by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '404':
          description: Entity not found
        '500':
          description: Internal server error
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: Doe
    Event:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Concert
        date:
          type: string
          format: date
          example: '2023-12-01'
    Ticket:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        user_id:
          type: integer
          format: int64
          example: 1
        event_id:
          type: integer
          format: int64
          example: 1
        status:
          type: string
          enum: ['booked', 'sold', 'canceled']