# Generated by Django 4.2.7 on 2023-12-06 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketapp', '0004_event_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(through='ticketapp.Ticket', to=settings.AUTH_USER_MODEL),
        ),
    ]
